name       : python-pybind11
version    : 2.2.2
release    : 1
source     :
    - https://github.com/pybind/pybind11/archive/v2.2.2.tar.gz : b639a2b2cbf1c467849660801c4665ffc1a4d0a9e153ae1996ed6f21c492064e
license    : BSD
component  : programming.python
summary    : Seamless operability between C++11 and Python
description: |
    pybind11 is a lightweight header-only library that exposes C++ types in Python and vice versa,
    mainly to create Python bindings of existing C++ code.
libsplit   : no
patterns   :
    - /usr/include
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup

    pwd
    mkdir -p build
    pushd build
    %cmake -DPYBIND11_CMAKECONFIG_INSTALL_DIR=lib64/cmake/pybind11 ..
    %make
    popd
install    : |
    %python_install
    %python3_install

    pushd build
    %make install
    popd
check      : |
    %make check
