name       : python-dask
version    : 0.17.2
release    : 1
source     :
    - https://github.com/dask/dask/archive/0.17.2.tar.gz : b72c1a19e9a90d9ae9028a3a15b18a831789590d26f6056bffa8ff5d1c51def3
license    : BSD
component  : programming.python
summary    : A flexible parallel computing library for analytic computing
description: |
    Dask is a flexible parallel computing library for analytic computing.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
