name       : python-absl-py
version    : 0.6.1
release    : 1
source     :
    - https://github.com/abseil/abseil-py/archive/pypi-v0.6.1.tar.gz : 6bc7189b0730ab6ab176d9cea406f352a489709b9c41d04fbed3dc2256a50bb6
license    : Apache-2.0
component  : programming.python
summary    : Abseil Python Common Libraries
description: |
    Abseil Python Common Libraries
builddeps  :
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
