name       : python-absl-py
version    : 0.1.13
release    : 1
source     :
    - https://github.com/abseil/abseil-py/archive/pypi-v0.1.13.tar.gz : 50c7a80a267f772b5d0cabf1ed043daa470aa73d613fd442b40ea451646c44d0
license    : Apache-2.0
component  : programming.python
summary    : Abseil Python Common Libraries
description: |
    Abseil Python Common Libraries
builddeps  :
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
