name       : xcb-imdkit
version    : 1.0.3
release    : 1
source     :
    - https://github.com/fcitx/xcb-imdkit/archive/refs/tags/1.0.3.tar.gz : 432452c092951f65fb738f19dfd28874ab971852cccfba0abef972699416a535
license    : LGPL-2.1-only
component  : xorg.library
summary    : Input method development support for xcb
description: |
    xcb-imdkit is an implementation of xim protocol in xcb, comparing with the implementation of IMDkit with Xlib, and xim inside Xlib, it has less memory foot print, better performance, and safer on malformed client.
builddeps  :
    - pkgconfig(uthash)
    - pkgconfig(xcb)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-util)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
