name       : python-tqdm
version    : 4.19.9
release    : 1
source     :
    - https://github.com/tqdm/tqdm/archive/v4.19.9.tar.gz : f2759bf16158ac12504c771b3dbe421767cebebcdf69a835725c386955fd2037
license    : MPL-2.0 and MIT
component  : programming.python
summary    : A fast, extensible progress bar for Python and CLI
description: |
    A fast, extensible progress bar for Python and CLI
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
