name       : ctpv
version    : 1.0
release    : 1
source     :
    - git|https://github.com/NikitaIvanovV/ctpv : 6d5c14d279a71d676270151d218efef067733921
license    : MIT
component  : system.utils
summary    : Terminal previewer
description: |
    ctpv is a previewer utility for terminals.
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX%
