name       : python-pytorch-gpu
version    : 1.0.0
release    : 1
source     :
    - git|https://github.com/pytorch/pytorch : v1.0.0
license    : BSD-3-Clause
component  : programming.python
summary    : Tensors and Dynamic neural networks in Python with strong GPU acceleration
description: |
    PyTorch is an optimized tensor library for deep learning using GPUs and CPUs
networking : yes
builddeps  :
    - pkgconfig(ompi)
    - pkgconfig(openblas)
    #- pkgconfig(protobuf) # If we want tensorrt
    - pkgconfig(python3)
    - numpy
    - python-setuptools
    - python-typing
    - pyyaml
    - g++-7
    - libgcc-7
    - libgomp-7
    - libstdc++-7
    - nvidia-glx-driver-common
    - pkgconfig(cuda)
    - cudnn-devel
    - nccl-devel
    - tensorrt-devel
    - mkl-dnn-devel
rundeps    :
    - numpy
    - python-cffi
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/nvtoolsext.patch
build      : |
    export CC=/usr/local/bin/gcc
    export CXX=/usr/local/bin/g++
    export CUDNN_INCLUDE_DIR=/usr/include/cuda
    #export EXTRA_CAFFE2_CMAKE_FLAGS="-DCUDA_TOOLKIT_ROOT_DIR=/usr/share/cuda -DUSE_TENSORRT=ON -DCCACHE_WRAPPER_PATH=/usr/local/bin -DCMAKE_VERBOSE_MAKEFILE=ON"
    export EXTRA_CAFFE2_CMAKE_FLAGS="-DCUDA_TOOLKIT_ROOT_DIR=/usr/share/cuda -DCCACHE_WRAPPER_PATH=/usr/local/bin"
    %python3_setup
install    : |
    %python3_install --skip-build
