name       : boostnote
version    : 0.11.3
release    : 1
source     :
    - https://github.com/BoostIO/Boostnote/archive/v0.11.3.tar.gz : aed079783f3f456dd6be84846128591dafc5cce7f425be97911bbc30a0bf3fde
license    : GPL-3.0
component  : office.notes
summary    : The opensource note app for developer.
description: |
    The note-taking app for programmers that focuses on markdown, snippets, and customizability.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-x11-2.0)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xtst)
    - git
    - nodejs
setup      : |
    mkdir -p grunt-install
    npm install --prefix grunt-install grunt-cli
    npm install --no-optional
build      : |
    grunt-install/node_modules/grunt-cli/bin/grunt pre-build
install    : |
    rm -rf $workdir/dist/Boostnote-linux-x64/resources/app/grunt-install

    install -dm00644 $installdir/usr/share/boostnote
    cp -R $workdir/dist/Boostnote-linux-x64/* $installdir/usr/share/boostnote

    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/boostnote/Boostnote $installdir/usr/bin/boostnote
    install -Dm00644 $pkgfiles/boostnote.desktop $installdir/usr/share/applications/boostnote.desktop

    install -Dm00644 $pkgfiles/boostnote.png $installdir/usr/share/pixmaps/boostnote.png
