name       : pasystray
version    : 0.8.2
release    : 2
source     :
    - https://github.com/christophgysin/pasystray/archive/refs/tags/0.8.2.tar.gz : 9c6fc5859a203f0a6dd8ce2038fea85b7bac44b1baff5c4cf73643229fafa641
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : PulseAudio system tray
description: |
    A replacement for the deprecated padevchooser. pasystray allows setting the default PulseAudio source/sink and moving streams on the fly between sources/sinks without restarting the client applications.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(avahi-client)
    - pkgconfig(libnotify)
    - pkgconfig(appindicator3-0.1)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
