name       : xfig
version    : 3.2.7a
release    : 1
source     :
    - https://sourceforge.net/projects/mcj/files/xfig-full-3.2.7a.tar.xz : 942ee7d3a241fd190bb9499ef16c2bc6bf9397395d52f16055459248ce91fea8
license    : MIT
component  : multimedia.graphics
summary    : Xfig is a free and open-source vector graphics editor which runs under the X Window System on most UNIX-compatible platforms.
description: |
    Xfig is a free and open-source vector graphics editor which runs under the X Window System on most UNIX-compatible platforms.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(x11)
      #- pkgconfig(xaw3d)
    - pkgconfig(xaw7)
    - pkgconfig(xt)
setup      : |
    pushd xfig-$version
    %configure --without-xaw3d
    popd

    pushd fig2dev-$version
    %configure
    popd
build      : |
    pushd xfig-$version
    %make
    popd

    pushd fig2dev-$version
    %make
    popd
install    : |
    pushd xfig-$version
    %make_install
    popd

    pushd fig2dev-$version
    %make_install
    popd
