name       : lgi
version    : 0.9.2
release    : 1
source     :
    - https://github.com/lgi-devs/lgi/archive/refs/tags/0.9.2.tar.gz : cfc4105482b4730b3a40097c9d9e7e35c46df2fb255370bdeb2f45a886548c4f
license    : MIT
component  : programming
summary    : Dynamic Lua binding to GObject libraries using GObject-Introspection
description: |
    LGI is gobject-introspection based dynamic Lua binding to GObject based libraries. It allows using GObject-based libraries directly from Lua.
builddeps  :
    - pkgconfig(lua)
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX% LUA_VERSION=5.3
