name       : sioyek
version    : 2.0.0
release    : 7
source     :
    - git|https://github.com/ahrm/sioyek : v2.0.0
license    : GPL-3.0-or-later
component  : office.viewers
summary    : A PDF viewer designed for reading research papers and technical books
description: |
    Sioyek is a PDF viewer designed for reading research papers and technical books.
builddeps  :
    - pkgconfig(Qt53DCore)
    - pkgconfig(freetype2)
    - pkgconfig(glut)
    - pkgconfig(harfbuzz)
    - pkgconfig(glu)
setup      : |
    sed -i 's/\/etc\/sioyek/\/usr\/share\/sioyek/' pdf_viewer/main.cpp
    sed -i 's/\/etc\/sioyek/\/share\/sioyek/' pdf_viewer_build_config.pro
build      : |
    pushd mupdf
    %make USE_SYSTEM_HARFBUZZ=yes USE_SYSTEM_GLUT=yes
    popd

    %qmake CONFIG+="linux_app_image" DEFINES+="LINUX_STANDARD_PATHS" pdf_viewer_build_config.pro
    %make
install    : |
    %make_install PREFIX=%PREFIX% INSTALL_ROOT="%installroot%"
    install -Dm00644 resources/sioyek.1 $installdir/usr/share/man/man1/sioyek.1
