name       : mkl-dnn
version    : 0.17.1
release    : 1
source     :
    - https://github.com/intel/mkl-dnn/archive/v0.17.2.tar.gz : 56c3e22d4fad816059cc58fd8e78ab3bacbec76a6bbded7eaead66220d8e5134
    - https://github.com/intel/mkl-dnn/releases/download/v0.17.2/mklml_lnx_2019.0.1.20181227.tgz : 0a8b39dd63494b1c5f55ef0eb7cd9a4f8cc3bcba09177b20a078c2b47e00f677
license    : Apache-2.0
component  : programming
summary    : Intel(R) Math Kernel Library for Deep Neural Networks (Intel(R) MKL-DNN)
description: |
    Intel(R) Math Kernel Library for Deep Neural Networks (Intel(R) MKL-DNN) is an open source performance library for deep learning applications.
    The library accelerates deep learning applications and framework on Intel(R) architecture.
    Intel(R) MKL-DNN contains vectorized and threaded building blocks which you can use to implement deep neural networks (DNN) with C and C++ interfaces.
patterns   :
    - /usr/lib/libiomp5.so
    - /usr/lib/libmklml_intel.so
    #builddeps  :
setup      : |
    mkdir -p build external
    MKL_NAME=$(basename $sources/mklml_lnx_*.tgz)
    tar -zxvf $sources/$MKL_NAME -C external
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
check      : |
    pushd build
    %make test
    popd
