name       : python-tensorboard
version    : 1.10.0
release    : 2
source     :
    - https://github.com/tensorflow/tensorboard/archive/1.10.0.tar.gz : d003ee154e8ae85b0f8a34fd7f8bb82a7f0acface8ca80db982b3595e401794f
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow's Visualization Toolkit
description: |
    TensorBoard is a suite of web applications for inspecting
    and understanding your TensorFlow runs and graphs.
networking : yes
builddeps  :
    - bazel
    - virtualenv
rundeps    :
    - numpy
    - python-bleach
    - python-markdown
    - python-protobuf
    #- python-tensorflow
    - python-wheel
    - python-werkzeug
setup      : |
    bazel build //tensorboard/pip_package:build_pip_package

    RUNFILES=bazel-bin/tensorboard/pip_package/build_pip_package.runfiles/org_tensorflow_tensorboard
    mkdir -p $PKG_BUILD_DIR/pkg
    cp -LR $RUNFILES/tensorboard $PKG_BUILD_DIR/pkg
    pushd $PKG_BUILD_DIR/pkg
    mv -f tensorboard/pip_package/setup.py .
    mv -f tensorboard/pip_package/setup.cfg .
    mv -f tensorboard/pip_package/MANIFEST.in .
    mv -f tensorboard/pip_package/LICENSE .
    mv -f tensorboard/pip_package/README.rst .

    rm -rf tensorboard/pip_package
    rm -f tensorboard/tensorboard

    chmod -x LICENSE
    popd

    bazel shutdown
build      : |
    pushd $PKG_BUILD_DIR/pkg
    python3 setup.py build
    popd
install    : |
    pushd $PKG_BUILD_DIR/pkg
    python3 setup.py install --root="%installroot%"
    popd
