name       : python-joblib
version    : 0.11
release    : 1
source     :
    - https://github.com/joblib/joblib/archive/0.11.tar.gz : 40b2fe577a5004ab48786678ee254735f50a5b7e741708c556c1bb87e87c118a
license    : BSD-3-Clause
component  : programming.python
summary    : Python function as pipeline jobs.
description: |
    Joblib is a set of tools to provide lightweight pipelining in Python.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
