name       : scikit-image
version    : 0.13.1
release    : 1
source     :
    - https://github.com/scikit-image/scikit-image/archive/v0.13.1.tar.gz : c38511f20145e14c28c42aac013b7714dc30a72a8a3e69db297f6b85d3b92f3e
license    : BSD-3-Clause
component  : programming.python
summary    : Image processing in Python
description: |
    scikit-image is a collection of algorithms for image processing.
builddeps  :
    - cython
    - numpy
    - python-setuptools
rundeps    :
    - matplotlib
    - networkx
    #- python-pywavelets
    - scipy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
