name       : lightgbm
version    : 2.1.0
release    : 1
source     :
    - https://github.com/Microsoft/LightGBM/archive/v2.1.0.tar.gz : 4b5ec7269b92d9473837db57f4ea9984e837561ba7885cbb2e830b0b89bcc214
license    : MIT
component  : programming
summary    : Light Gradient Boosting Machine
description: |
    LightGBM is a fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework
    based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.
patterns   :
    - /usr/include
    - /usr/lib
builddeps  :
    - pkgconfig(ompi)
    - pkgconfig(OpenCL)
    - libboost-devel
    - python-setuptools
setup      : |
    mkdir -p build
    pushd build
    %cmake -DUSE_MPI=ON -DUSE_GPU=ON ..
    popd
build      : |
    pushd build
    %make
    popd

    cp -r python-package py2build
    cp -r python-package py3build

    pushd py2build
    python2.7 setup.py build
    popd

    pushd py3build
    python3 setup.py build
    popd
install    : |
    pushd build
    %make_install
    popd

    pushd py2build
    python2.7 setup.py install --root="%installroot%" --mpi --gpu
    popd

    pushd py3build
    python3 setup.py install --root="%installroot%" --mpi --gpu
