name       : caffe
version    : 1.0
release    : 1
source     :
    - https://github.com/BVLC/caffe/archive/1.0.tar.gz : 71d3c9eb8a183150f965a465824d01fe82826c22505f7aa314f700ace03fa77f
license    : BSD-2-Clause
component  : programming.tools
summary    : A fast open framework for deep learning
description: |
    Caffe is a deep learning framework made with expression, speed, and modularity in mind
builddeps  :
    - pkgconfig(gflags)
    - pkgconfig(libglog)
    - pkgconfig(openblas)
    - pkgconfig(opencv)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - hdf5-devel
    - leveldb-devel
    - libboost-devel
    - lmdb-devel
    - numpy
#rundeps    :
    #- scikit-image
setup      : |
    %patch -p1 < $pkgfiles/0001-Makefile-config.patch
    mv Makefile.config.example Makefile.config
build      : |
    %make

    cp -r python py3build
    mv python py2build

    ln -s py2build python
    %make pycaffe
    unlink python

    %patch -p1 < $pkgfiles/0002-enable-python3.patch
    ln -s py3build python
    %make pycaffe
    # The python symlink is kept since it's needed in make distribute
    
    %make distribute
install    : |
    for file in distribute/bin/*.bin
    do
        mv "$file" "${file%%.bin}"
    done
    install -dm00755 $installdir/usr/bin
    cp -R distribute/bin/* $installdir/usr/bin

    rm -rf distribute/lib/*.a
    install -dm00755 $installdir/usr/lib64
    cp -R distribute/lib/* $installdir/usr/lib64

    install -dm00644 $installdir/usr/include
    cp -R distribute/include/* $installdir/usr/include

    install -dm00644 $installdir/usr/share/caffe
    cp -R distribute/proto/* $installdir/usr/share/caffe

    mkdir -p $installdir/usr/share/caffe/examples
    cp -R py3build/*.py $installdir/usr/share/caffe/examples

    mkdir -p $installdir/usr/lib/python2.7/site-packages
    cp -R pybuild2/caffe $installdir/usr/lib/python2.7/site-packages

    mkdir -p $installdir/usr/lib/python3.6/site-packages
    cp -R pybuild3/caffe $installdir/usr/lib/python3.6/site-packages

    #%make distribute DISTRIBUTE_DIR=$installdir/usr
    #chmod 755 $installdir/usr/bin/* # Do I need to do this?
    #for file in $installdir/usr/bin/*.bin
    #do
    #    mv "$file" "${file%%.bin}"
    #done

    #find $installdir/usr/include/caffe -type f -print0 | xargs -0 chmod 644
    #chmod 755 $installdir/usr/lib/libcaffe.so.1.0.0
    #rm -rf $installdir/usr/lib/libcaffe.a
check      : |
    %make test
    %make runtest
