name       : xgboost
version    : 0.80
release    : 1
source     :
    - https://github.com/dmlc/xgboost/releases/download/v0.80/xgboost-0.80.tar.bz2 : 9aecbde00296f04e0e5e4981d94bb7f739a865e55b4afb530bc77e9023b7e260
license    : Apache-2.0
component  : programming
summary    : Scalable, portable and distributed gradient boosting library
description: |
    XGBoost is an optimized distributed gradient boosting library
    designed to be highly efficient, flexible and portable.
networking : yes
patterns   : 
    - /usr/include
    - /usr/lib64
builddeps  :
    - git
    - python-setuptools
rundeps    :
    - scipy
setup      : |
    git init

    nmodules=$(git config --file .gitmodules --get-regexp path | wc -l)

    for i in $(seq 1 $nmodules)
    do
        path=$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }' | sed -n ${i}p)
        url=$(git config --file .gitmodules --get-regexp url | awk '{ print $2 }' | sed -n ${i}p)
        rm -rf $path
        git submodule add -f $url $path
    done

    %patch -p1 < $pkgfiles/0001-do-not-override-solus-default-flags.patch
build      : |
    %make

    cp -a python-package py2build
    cp -a python-package py3build

    pushd py2build
    python2.7 setup.py build
    popd

    pushd py3build
    python3 setup.py build
    popd
install    : |
    install -dm00755 $installdir/usr/include
    cp -r include/* $installdir/usr/include

    install -dm00755 $installdir/usr/lib64
    cp -r lib/*.so $installdir/usr/lib64

    install -dm00755 $installdir/usr/bin
    cp -r xgboost $installdir/usr/bin

    pushd py2build
    python2.7 setup.py install --root="%installroot%"
    popd
    
    pushd py3build
    python3 setup.py install --root="%installroot%"
    popd

    rm -rf $installdir/usr/xgboost
