name       : python-protobuf
version    : 3.5.1
release    : 1
source     :
    - https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-python-3.5.1.tar.gz : 13d3c15ebfad8c28bee203dd4a0f6e600d2a7d2243bac8b5d0e517466500fcae
license    : BSD-3-Clause
component  : programming.python
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(protobuf)
    - python-setuptools
rundeps    :
    - python-setuptools
    - python-six
setup      : |
    cp -a python py2build
    cp -a python py3build
build      : |
    pushd py2build 
    python2 setup.py build --cpp_implementation
    popd

    pushd py3build
    python3 setup.py build --cpp_implementation
    popd
install    : |
    pushd py2build
    python2 setup.py install --root="%installroot%" --cpp_implementation
    popd

    pushd py3build
    python3 setup.py install --root="%installroot%" --cpp_implementation
    popd
