name       : python-protobuf
version    : 3.5.1
release    : 1
source     :
    - https://pypi.python.org/packages/14/03/ff5279abda7b46e9538bfb1411d42831b7e65c460d73831ed2445649bc02/protobuf-3.5.1.tar.gz : 95b78959572de7d7fafa3acb718ed71f482932ddddddbd29ba8319c10639d863
license    : BSD-3-Clause
component  : programming.python
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
