name       : fortisslvpn
version    : 1.1.0
release    : 6
source     :
    - git|https://github.com/gm-vm/openfortivpn-webview : v1.1.0-electron
license    : MIT
component  : network.util
summary    : FortiSSL VPN Client
description: |
    FortiSSL VPN Client
builddeps  :
    - pkgconfig(Qt5WebEngine)
rundeps    :
    - openfortivpn
    - yad
setup      : |
    pushd openfortivpn-webview-qt
    %qmake .
    popd
build      : |
    %make -C openfortivpn-webview-qt
install    : |
    install -dm00755 $installdir/usr/bin $installdir/usr/share/fortisslvpn/templates
    install -Dm00755 openfortivpn-webview-qt/openfortivpn-webview $installdir/usr/bin/openfortivpn-webview
    install -Dm00755 $pkgfiles/fortisslvpn-saml $installdir/usr/bin/fortisslvpn-saml
    install -Dm00755 $pkgfiles/fortisslvpn-cli $installdir/usr/share/fortisslvpn/fortisslvpn-cli
    install -Dm00644 $pkgfiles/fortisslvpn.desktop $installdir/usr/share/fortisslvpn/templates/fortisslvpn.desktop
    install -Dm00644 $pkgfiles/org.fortisslvpn.policy $installdir/usr/share/polkit-1/actions/org.fortisslvpn.policy
