name       : python-h5py
version    : 2.8.0_rc1
release    : 1
source     :
    - https://github.com/h5py/h5py/archive/2.8.0rc1.tar.gz : 9d0e469bc9002381c13f69a560a3476ef1b05186796c9f6c2d2e06981cf9fe17
license    : BSD
component  : programming.python
summary    : Pythonic interface to the HDF5 binary data format
description: |
    The h5py package is a Pythonic interface to the HDF5 binary data format
builddeps  :
    - cython
    - hdf5-devel
    - numpy
    - python-pkgconfig
    - python-setuptools
    - python-six
rundeps    :
    - numpy
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
