name       : kopia
version    : 0.12.1
release    : 1
source     :
    - git|https://github.com/kopia/kopia.git : v0.12.1
license    : Apache-2.0
component  : system.utils
networking : yes
summary    : A fast and secure open-source backup/restore tool
description: |
    Kopia is a fast and secure open-source backup/restore tool that allows you to create encrypted snapshots of your data and save the snapshots to remote or cloud storage of your choice, to network-attached storage or server, or locally on your machine. Kopia does not 'image' your whole machine. Rather, Kopia allows you to backup/restore any and all files/directories that you deem are important or critical.
builddeps  :
    - golang
build      : |
    go build -ldflags "-s -w" -o kopia
    ./kopia --help-man > kopia.1
    ./kopia --completion-script-bash > kopia.bash
    ./kopia --completion-script-zsh > kopia.zsh
install    : |
    install -Dm00755 kopia $installdir/usr/bin/kopia
    install -Dm00644 kopia.bash $installdir/usr/share/bash-completion/completions/kopia
    install -Dm00644 kopia.zsh $installdir/usr/share/zsh/site-functions/_kopia
    install -Dm00644 kopia.1 $installdir/usr/share/man/man1/kopia.1
