name       : mupdf
version    : 1.13.0
release    : 1
source     :
    - https://github.com/ArtifexSoftware/mupdf/archive/1.13.0.tar.gz : 10370d077d08b57460aa9901cb66a0646095870caa6e6f224902a8cd5473a458
license    : AGPL-3.0
component  : office.viewers
summary    : A lightweight PDF, XPS, and E-book viewer
description: |
    MuPDF is a lightweight open source software framework for viewing and converting PDF, XPS, and E-book documents.
libsplit   : no
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(openssl)
    - pkgconfig(xrandr)
    - ghostscript-devel
    - jbig2dec-devel
setup      : |
    %patch -p1 < $pkgfiles/mupdf-1.13.0-shared_libs-1.patch
    rm -rf thirdparty/*
build      : |
    XCFLAGS="-fPIC" %make
install    : |
    prefix=/usr %make_install

    # Set proper permission bits
    chmod 644 $installdir/usr/share/man/man1/*.1
    find $installdir/usr/share/doc/mupdf -type f -print0 | xargs -0 chmod 644
    find $installdir/usr/include/mupdf -type f -print0 | xargs -0 chmod 644

    ln -sv /usr/bin/mupdf-x11 $installdir/usr/bin/mupdf

    install -Dm00644 $pkgfiles/mupdf.desktop $installdir/usr/share/applications/mupdf.desktop
    install -Dm00755 $pkgfiles/mupdf-select-file $installdir/usr/bin/mupdf-select-file

    install -Dm00644 $pkgfiles/mupdf.png $installdir/usr/share/pixmaps/mupdf.png
