name       : jbig2dec
version    : 0.14
release    : 1
source     :
    - https://github.com/ArtifexSoftware/jbig2dec/archive/0.14.tar.gz : cf8368d8d5b63f2e4a993b49b95656e0090f1f419d4c2f0841a0cde75c9f34b0
license    : AGPL
component  : multimedia.graphics
summary    : Decoder implementation of the JBIG2 image compression format.
description: |
    jbig2dec is a decoder library and example utility implementing the JBIG2
    bi-level image compression spec. Also known as ITU T.88 and ISO IEC
    14492, and included by reference in Adobe's PDF version 1.4 and later.
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install

    # Remove the static library
    rm -v $installdir/usr/lib64/lib*.a
