name       : cuda
version    : 10.0.130
release    : 1
source     :
    - https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux : 92351f0e4346694d0fcb4ea1539856c9eb82060c25654463bfd8574ec35ee39a
extract    : no
license    : EULA
component  : programming.tools
summary    : NVIDIA's GPU programming toolkit
description: |
    CUDA® is a parallel computing platform and programming model developed
    by NVIDIA for general computing on graphical processing units (GPUs).
strip      : no
patterns   :
    - devel : /usr/share/cuda/include
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(glu)
    - pkgconfig(libglvnd)
    - chrpath
setup      : |
    CUDA_INSTALL_FILE=$(basename $sources/cuda_${version}_*_linux*)
    sh $sources/$CUDA_INSTALL_FILE --extract=$workdir
build      : |
    ./cuda-linux.${version}-*.run -noprompt -nosymlink -no-man-page -prefix=$PKG_BUILD_DIR/cuda_build
    ./cuda-samples.${version}-*.run -noprompt -prefix=$PKG_BUILD_DIR/cuda_build/samples -cudaprefix=/usr

    pushd $PKG_BUILD_DIR/cuda_build
    %patch -p1 < $pkgfiles/gcc-8.patch
    popd
install    : |
    #install -Dm00644 $pkgfiles/cuda.sh $installdir/usr/share/defaults/etc/profile.d/cuda.sh

    # nsight and nvvp are not packaged at the moment

    pushd $PKG_BUILD_DIR/cuda_build

    # doc
    install -dm00755 $installdir/usr/share/doc/cuda
    cp -r doc/html $installdir/usr/share/doc/cuda
    cp -r doc/pdf $installdir/usr/share/doc/cuda

    install -dm00755 $installdir/usr/share/man/man{1,7}
    install -Dm00644 -t $installdir/usr/share/man/man1 doc/man/man1/*
    install -Dm00644 -t $installdir/usr/share/man/man7 doc/man/man7/*
    rm -v $installdir/usr/share/man/man1/nsight.*
    rm -v $installdir/usr/share/man/man1/nvvp.*

    # Deal with binaries
    install -dm00755 $installdir/usr/bin
    cp -r bin/* $installdir/usr/bin
    find $installdir/usr/bin -type f -name "*install*" -delete
    find $installdir/usr/bin -type f -name "*nsight*" -delete
    find $installdir/usr/bin -type f -name "*nvvp*" -delete
    unlink $installdir/usr/bin/computeprof
    rm -v $installdir/usr/bin/nvcc.profile
    install -Dm00644 $pkgfiles/nvcc.profile $installdir/usr/bin

    # Header files
    install -dm00755 $installdir/usr/include/cuda
    cp -r include/* $installdir/usr/include/cuda
    find $installdir/usr/include/cuda -type f -print0 | xargs -0 chmod 644
    install -dm00755 $installdir/usr/share/cuda
    ln -s /usr/include/cuda $installdir/usr/share/cuda/include

    # Libraries
    # We don't use the libraries in `stubs` subdir
    install -dm00755 $installdir/usr/lib64
    cp -r lib64/lib*.so* $installdir/usr/lib64
    cp -r lib64/lib*.a $installdir/usr/lib64
    # Remove OpenCL
    rm -v $installdir/usr/lib64/libOpenCL.so*
    #install -dm00755 $installdir/usr/lib64/cuda/stubs
    #install -Dm00755 -t $installdir/usr/lib64/cuda/stubs lib64/stubs/*

    # pkgconfig
    install -dm00755 $installdir/usr/lib64/pkgconfig
    install -Dm00644 -t $installdir/usr/lib64/pkgconfig $pkgfiles/*.pc

    # samples
    cp -r samples $installdir/usr/share/cuda
    find $installdir/usr/share/cuda/samples -type f -name "findgllib.mk" -print0 | 
        xargs -0 sed -i '57i\    GLPATH    ?= /usr/lib64/nvidia\n    GLLINK    ?= -L/usr/lib64/nvidia\n    DFLT_PATH ?= /usr/lib64'

    # nvvm
    cp -r nvvm/include/* $installdir/usr/include/cuda
    cp -r nvvm/lib64/* $installdir/usr/lib64
    cp -r nvvm/libdevice/* $installdir/usr/share/cuda
    cp -r nvvm/libnvvm-samples $installdir/usr/share/cuda/samples/nvvm
    install -Dm00755 nvvm/bin/cicc $installdir/usr/bin/cicc
    # Remove RUNPATH on binaries
    chrpath -d $installdir/usr/bin/cicc

    # extras/CUPTI
    install -dm00755 $installdir/usr/include/cuda/CUPTI
    cp -r extras/CUPTI/include/* $installdir/usr/include/cuda/CUPTI
    cp -r extras/CUPTI/lib64/* $installdir/usr/lib64
    cp -r extras/CUPTI/sample $installdir/usr/share/cuda/samples/CUPTI

    # nvml
    cp -r nvml/example $installdir/usr/share/cuda/samples/nvml

    # jre
    #rm -rv libnsight libnvvp nsightee_plugins jre

    # gdb
    cp -r share/gdb $installdir/usr/share/cuda/gdb
    cp -r extras/cuda-gdb* $installdir/usr/share/cuda/gdb

    # extras/Debugger
    install -dm00755 $installdir/usr/include/cuda/Debugger
    cp -r extras/Debugger/include/* $installdir/usr/include/cuda/Debugger
    cp -r extras/Debugger/lib64/* $installdir/usr/lib64

    # extras/demo_suite
    cp -r extras/demo_suite $installdir/usr/share/cuda

    # src
    install -dm00755 $installdir/usr/include/cuda/fortran
    cp src/* $installdir/usr/include/cuda/fortran

    # tools
    cp -r tools $installdir/usr/share/cuda

    # version.txt
    install -Dm00644 version.txt $installdir/usr/share/cuda/version.txt

    popd

    # Clean up
    find . -name "*.bat" -delete
    # Clean empty directories
    find $installdir/usr -type d -empty -delete
