name       : python-patsy
version    : 0.5.0
release    : 1
source     :
    - https://pypi.python.org/packages/8b/c7/c3f6ae21cd9bde9b434ffc5a451e2ba657a5a062d21ee41fe9990c739013/patsy-0.5.0.tar.gz : e05f38d5c38c8d216f0cc2b765b1069b433c92d628b954fb2fee68d13e42883b
license    : BSD-2-Clause
component  : programming.python
summary    : Python package for describing statistical models and building design matrices
description: |
    patsy is a Python package for describing statistical models (especially linear models,
    or models that have a linear component) and building design matrices. It is closely
    inspired by and compatible with the formula mini-language used in R and S.
builddeps  :
    - python-setuptools
rundeps    :
    - numpy
    - python-six
    - scipy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
