name       : python-pkgconfig
version    : 1.3.1
release    : 1
source     :
    - https://github.com/matze/pkgconfig/archive/v1.3.1.tar.gz : b4b8277cf33df2bfdd73da2bc4faab1b4b65b6d12e295aa6c70987642bcfb5c7
license    : MIT
component  : programming.python
summary    : A Python interface to the pkg-config command line tool
description: |
    A Python interface to the pkg-config command line tool
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
